### ISSUE TITLE
function read_list() returns error when following book example

### ISSUE THREAD

**Issue by Triamus** [b-rodrigues/functional_programming_and_unit_testing_for_data_munging#1]
following book example [6.2.1 Reading a lot of datasets at once](http://www.brodrigues.co/fput/putting-it-all-together-writing-a-package-to-work-on-data.html), following call throws below error.

datasets <- read_list(list_of_data, read_csv, col_type = cols())

Error in names(output) <- names_of_datasets : 
 'names' attribute [8] must be the same length as the vector [5]

**Comment by b-rodrigues** [comment]
Thanks, I will look into it this weekend. In the meantime could you please provide more details, such as the exact error message and your code? Did you put all the datasets into a list?

**Comment by Triamus** [comment]
Here a reproducible snippet. I was also wondering about the double assignment to "dataset_name" in the function read_and_assign() but haven't tried any debugging.

    path <- "D:/github/repos/fput-gh-pages/assets"
    setwd(path)
    
    read_list <- function(list_of_datasets, read_func, ...){
    
      stopifnot(length(list_of_datasets)>0)
  
      read_and_assign <- function(dataset, read_func){
        dataset_name <- as.name(dataset)
        dataset_name <- read_func(dataset, ...)
      }
  
      # invisible is used to suppress the unneeded output
      output <- invisible(
        purrr::map(list_of_datasets,
                   read_and_assign,
                   read_func = read_func)
      )
  
      # Remove the ".csv" at the end of the data set names
      names_of_datasets <- c(unlist(strsplit(list_of_datasets, "[.]"))[c(T, F)])
      names(output) <- names_of_datasets
      return(output)
    }

    library("readr")
    library("purrr")
    library("tibble")

    list_of_data <- Sys.glob("./*.csv")
    list_of_data
    #> "./data_2000.csv" "./data_2001.csv" "./data_2002.csv" "./data_2003.csv" "./data_2004.csv"

    datasets <- read_list(list_of_data, read_csv, col_type = cols())
    #> Error in names(output) <- names_of_datasets : 
    #>  'names' attribute [8] must be the same length as the vector [5]

**Comment by b-rodrigues** [comment]
I'm not in front of my computer, but I believe the problem comes from the "." character in "/.". Because I use a regexp to separate the names of the datasets from the extension with "[.]", I believe the names get split at different points and this pollutes the list containing the names, making it longer. Try to print the list of names and I think you'll see this is the issue. 

On January 14, 2017 1:42:17 PM GMT+01:00, Triamus <notifications@github.com> wrote:
>Here a reproducible snippet. I was also wondering about the double
>assignment to "dataset_name" in the function read_and_assign() but
>haven't tried any debugging.
>
>    path <- "D:/github/repos/fput-gh-pages/assets"
>    setwd(path)
>    
>    read_list <- function(list_of_datasets, read_func, ...){
>    
>      stopifnot(length(list_of_datasets)>0)
>  
>      read_and_assign <- function(dataset, read_func){
>        dataset_name <- as.name(dataset)
>        dataset_name <- read_func(dataset, ...)
>      }
>  
>      # invisible is used to suppress the unneeded output
>      output <- invisible(
>        purrr::map(list_of_datasets,
>                   read_and_assign,
>                   read_func = read_func)
>      )
>  
>      # Remove the ".csv" at the end of the data set names
>names_of_datasets <- c(unlist(strsplit(list_of_datasets, "[.]"))[c(T,
>F)])
>      names(output) <- names_of_datasets
>      return(output)
>    }
>
>    library("readr")
>    library("purrr")
>    library("tibble")
>
>    list_of_data <- Sys.glob("./*.csv")
>    list_of_data
>#> "./data_2000.csv" "./data_2001.csv" "./data_2002.csv"
>"./data_2003.csv" "./data_2004.csv"
>
>    datasets <- read_list(list_of_data, read_csv, col_type = cols())
>    #> Error in names(output) <- names_of_datasets : 
>    #>  'names' attribute [8] must be the same length as the vector [5]
>
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/b-rodrigues/fput/issues/1#issuecomment-272621842

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by Triamus** [comment]
Sorry was hitting wrong button on mobile and accidently closed issue. I'll try with different syntax once on a pc.

**Comment by Triamus** [comment]
As you guessed, issue seems to be caused by regex processing "./*.csv" notation. Below works as expected.

    list_of_data <- Sys.glob("D:/github/repos/fput-gh-pages/assets/*.csv")

**Comment by b-rodrigues** [comment]
Great, I will think about how avoiding this issue in the future.
